# Q Learning the Taxi-v2 environment
> Q Table actually, me a noob

In [2]:
import numpy as np
import gym
import random 

env = gym.make('Taxi-v2')
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [4]:
print(env.action_space)
print(env.observation_space)

Discrete(6)
Discrete(500)


In [7]:
#Initialize Q-table with zeros. States as rows, action as cols
qtable = np.zeros((env.observation_space.n, env.action_space.n)) 
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
total_episodes = 50000
total_test_episodes = 100
max_steps = 99

learning_rate = 0.7
gamma = 0.618

epsilon = 1  #epsilon exploration criterion
max_epsilon= 1.0
min_epsilon = 0.01
decay_rate = 0.01
#Need to decay epsilon as we need a higher exploration rate at the beginning

### Q learning alg

In [27]:
for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        if random.uniform(0, 1) > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample()  #random action with probability epsilon
        
        new_state, reward, done, info = env.step(action)
        #Q(s, a) = Q(s, a) + lr*[R(s, a) + y*maxQ(s', a') - Q(s, a)]
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * 
                                    np.max(qtable[new_state, :]) - qtable[state, action]) 
    
        state = new_state
        if done == True:
            break
    
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)


### Play 

In [28]:
env.reset()
rewards = []

for episode in range(total_test_episodes):  #100
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        #env.render()
        action = np.argmax(qtable[state, :])  #alredy learnt, so just exploit
        new_state, reward, done, _ = env.step(action)
        
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            break
        state = new_state
    print("Score for this episode: ", total_rewards)
env.close()
print("Score over time: " + str(sum(rewards)/total_test_episodes))   #average score over 100 eps
        

Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  7
Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  8
Score for this episode:  -99
Score for this episode:  10
Score for this episode:  11
Score for this episode:  6
Score for this episode:  13
Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  9
Score for this episode:  12
Score for this episode:  7
Score for this episode:  -99
Score for this episode:  8
Score for this episode:  4
Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  8
Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  14
Score for this episode:  8
Score for this episode:  10
Score for this episode:  11
Score for this episode:  -99
Score for this episode:  -99
Score for this episode:  8
Score for this episode:  8
Score for this

In [22]:
qtable

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ -2.61780105,  -2.61780105,  -2.61780105,  -2.61780105,
         -2.61780105, -11.61646471],
       [ -2.61780105,  -2.61780105,  -2.61780105,  -2.61780105,
         -2.61780105, -11.61540962],
       ...,
       [ -2.61780105,  -2.61780105,  -2.61780105,  -2.61780105,
        -11.61776364, -11.61780088],
       [ -2.61780105,  -2.61780105,  -2.61780105,  -2.61780105,
        -11.61779134, -11.61664061],
       [ -2.58422161,  -2.58789857,  -2.57196507,  -2.57196507,
         -7.        ,  -7.        ]])